### PR TITLE
Fixed grid traversal with near and far planes

### PR DESCRIPTION
**Pull request by arterms**
This PR fixes wrong points sampling behind the far_plane, as described in #201

### CODE REVIEW

**Comment by arterms** [comment]
Yes, I have checked this PR by printing out the returned intervals. It doesn't produce degenerated samples with intervals of zero length. Moreover I have added a test named `test_traverse_grids_with_near_far_planes` to verify that no points are sampled behind far_planes. As for me, with this fix the function works as expected. If I clearly understand the code, the [loop](https://github.com/KAIR-BAIR/nerfacc/blob/d858e9f3a6814d04d298c561f65469b05689047e/nerfacc/cuda/csrc/grid.cu#L141) of marching will be terminated as the sampled point exceeds the `t_traversal` value (clamped to far plane value).

**Comment by liruilong940607** [comment]
Hi to clarify, t_traverse is not the termination threshold. It is the *actual* t during marching, e.g., 0.1,0.2,0.3 etc. The tdist is also not a constant. It would be update by the single_traversal function within the loop.

Hopefully by far we are on the same page about what t_traverse is. Thus I don’t think clamping t_traverse would terminate the ray. In fact this value does not affect the loop at all. It is output/result ready to be written back.

So that’s why I believe clamping on t_traverse would result in zero length ray segments.

I might be able to test this on weekends but hopefully my explanation makes sense to you.

**Comment by liruilong940607** [comment]
Actually I revisited the code and I agree it would not create degenerated samples because of [this line](https://github.com/KAIR-BAIR/nerfacc/blob/d858e9f3a6814d04d298c561f65469b05689047e/nerfacc/cuda/csrc/grid.cu#L215). Yeah now I agree this is the right fix. I’ll merge it then. Thanks for the contribution!!

**Comment by liruilong940607** [comment]
There is a formatting test failure. You can fix it by running: 

```bash
pip install .[dev]
black docs/ nerfacc/ scripts/ examples/ tests/ --exclude examples/pycolmap --line-length 80
```

**Comment by arterms** [comment]
Just fixed the formatting

**Pull request merged**
