### PR TITLE
avoid Windows repeated CUDA setup

### PR DESCRIPTION
**Pull request by machenmusik**
restore working 0.2.1 version, since .so will not exist on Windows

### CODE REVIEW

**Comment by machenmusik** [comment]
See https://github.com/nerfstudio-project/nerfstudio/pull/1277#issuecomment-1402977484

**Review by tancik — APPROVED** [review]
LGTM

**Review by tancik — COMMENTED** [review]
Are there not cases where the build directory exists (ie for other cuda kernels), but he `nerfacc` one doesn't?

**Comment by machenmusik** [comment]
Note surprising result https://github.com/nerfstudio-project/nerfstudio/pull/1277#issuecomment-1404215735

I don't love directory check strategy, but that seems to be what actually works.

**Comment by liruilong940607** [comment]
Awesome thanks for the find.

**Pull request merged**
